services:
  - type: web
    runtime: python
    name: budget-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
